language: r
sudo: required
cache: packages

r_check_args: "--as-cran --run-dontrun"

r_packages:
  - covr

addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/jq'
    packages:
      - libjq-dev
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: YO8T9bcDOws/skyUehUe3p6FmooNgXh6yHpq4x2Nm9ROoHRBGfTOp+Aq4zds13ISokvxQEDW37wae7BbcteFAdLrxqyNHPnM/AnhCviiDSE/fcwMoOOsYreZGGazVGbIxsbK/OLH1nTva6Qow6e44QlahokFpO4Qjd6obvvIHSo=
